[project]
name = "coingecko-price-server-py"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
